import pyperclip
import re

port_type = {
    '0000': 'SLT',
    '0004': 'MLT',
    '000C': 'TRK',
    '0034': 'CCIS',
    '0040': 'VE',
    '00D0': 'IPT',
    '00DC': 'SIPT',
}
status = {
    '00H': 'IDLE',
    '01H': 'HOLD',
    '02H': 'DIAL_TN',
    '03H': 'CBK_TN',
    '04H': 'RGBK_TN',
    '05H': 'RBK_TRN',
    '06H': 'BUSY_TN',
    '07H': 'B_BUSY',
    '08H': 'CONGEST',
    '09H': 'WARNING',
    '0AH': 'CONFIRM',
    '0BH': 'CAL_WAT',
    '0CH': 'HELD',
    '0DH': 'RINGING',
    '0EH': 'CALLBK',
    '0FH': 'DIALING',
    '10H': 'DIAL_TR',
    '11H': 'SPEAK',
    '12H': 'READY',
    '13H': 'WORD_AC',
    '14H': 'LOCK',
    '15H': 'TRG_ACK',
    '16H': 'WHLD_AC',
    '17H': 'WCBK_AC',
    '18H': 'WATS_AC',
    '19H': 'WTCB_AC',
    '1AH': 'WBTS_AC',
    '1BH': 'WRGT_AC',
    '1CH': 'RGTS_AC',
    '1DH': 'WRBT_AC',
    '1EH': 'RRBT_AC',
    '1FH': 'RGTTR_AC',
    '20H': 'WPLT_AC',
    '21H': 'WBYP_AC',
    '22H': 'D_B_BSY',
    '23H': 'WAITING',
    '24H': 'CALLING',
    '25H': 'GUARD',
    '26H': 'CLEAR_W',
    '27H': 'RE_WAIT',
    '28H': 'RECEPT',
    '29H': 'BREAK',
    '2AH': 'EMS_BSY',
    '2BH': 'WAT_SUB',
    '2CH': 'WGRC_AC',
    '2DH': 'WPCB_AC',
    '2EH': 'PARKED',
    '2FH': 'CWAT_AC',
    '30H': 'PICK_AC',
    '31H': 'FMST_AC',
    '33H': 'WAIT_INC',
    '34H': 'WAT_ANS',
    '35H': 'CPST_AC',
    '36H': 'OHFK_CP',
    '37H': 'CMP_CBK',
    '38H': 'WCMP_AC',
    '39H': 'GRP_CAL',
    '3AH': 'WDMY_AC',
    '3BH': 'SRC_OFF',
    '3CH': 'GP_OVER',
    '3DH': 'MWSET_AC',
    '3EH': 'MWORD_AC',
    '3FH': 'MWANS_AC',
    '40H': 'WEHLD_AC',
    '41H': 'WGHLD_AC',
    '42H': 'CMP_RESV',
    '43H': 'WTRK_AC',
    '44H': 'EXTPAG',
    '45H': 'CPTRK_AC',
    '46H': 'I_MET_AN',
    '47H': 'WPAG_AC',
    '48H': 'I_MET_ME',
    '49H': 'RECONECT',
    '4AH': 'IDIALING',
    '4BH': 'VCALL',
    '4CH': 'IRGT_SAC',
    '4DH': 'IFLM_SAC',
    '4EH': 'WHOOK_AC',
    '4FH': 'WMON_AC',
    '50H': 'WCHLD_AC',
    '51H': 'WEHLDO_A',
    '52H': 'WIHLD_AC',
    '53H': 'ALM_RING',
    '54H': 'ALM_HOLD',
    '55H': 'WOFHS_AC',
    '56H': 'DOOR_MON',
    '57H': 'WEHLDSPA',
    '58H': 'E_MET_AN',
    '59H': 'E_MET_ME',
    '5AH': 'C_SPEAK_',
    '5BH': 'HELD$TRS',
    '5CH': 'W_C_INFO',
    '5DH': 'TXT_M_ED',
    '5EH': 'I_MET_CO',
    '5FH': 'E_MET_CO',
    '60H': 'C_SPK$M',
    '61H': 'IHELD',
    '62H': 'ICALLBK',
    '63H': 'WICBK_AC',
    '64H': 'INT_PAG',
    '65H': 'W_BRK_IN',
    '66H': 'WDOORP_A',
    '67H': 'SPEAK$B',
    '68H': 'WIHDO_AC',
    '69H': 'WEHLDB_A',
    '6AH': 'WTR_ACPS',
    '6BH': 'LOGON',
    '6CH': 'W_DIDSTA',
    '6DH': 'W_DIDPLT',
    '6EH': 'DID_S_CA',
    '6FH': 'W_CBK_RB',
    '70H': 'W_CBK_RG',
    '71H': 'W_OFDTY',
    '74H': 'W_MF_REC',
    '75H': 'CHAR_INP',
    '77H': 'SECR_ACK',
    '78H': 'ACC_DIAL',
    '79H': 'FAX_ON',
    '81H': 'BLK_INCM',
    '82H': 'ERR_STAT',
    '83H': 'ERR_ST_A',
    'B1H': 'CAL INIT',
    'B2H': 'OVRLAP S',
    'B3H': 'OTG CPRC',
    'B4H': 'CAL DELV',
    'B6H': 'CAL PRST',
    'B8H': 'CON REQ',
    'B9H': 'INC CPRC',
    'BBH': 'DISC REQ',
    'BCH': 'DISC IND',
    'BFH': 'SUSP REQ',
    'C1H': 'RESM REQ',
    'C3H': 'REL REQ',
    'C9H': 'OVRLAP R',
    'D0H': 'PRE CL I',
    'D1H': 'L2 ERR',
}

log_paste = pyperclip.paste()
# we will analyze such lines >>>> PORT:000C0011H  STATUS 000DH => 0011H
rx = re.compile(r'>>>> PORT:(\d\d\d.)\d\d(\d\d)H  STATUS ....H => \d\d(\d\dH)')
rows_found = re.findall(rx, log_paste)
for item in rows_found:
    print('%s %02d - %s' % (port_type[item[0]], int(item[1], 16),
                            status.get(item[2], item[2])))
    # TRK 17 - SPEAK

input()
